services:
  - type: web
    name: web-seeker-live-dashboard
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BOT_API_SECRET
        generateValue: true
